### ISSUE TITLE
rebrand py-autocrypt to .... 

### ISSUE THREAD

**Issue by hpk42** [hpk42/muacrypt#34]
This respository does not only aim to offer fully compliant and automatically tested autocrypt support but to also experiment with re-mailer integration (#30), out of band verification (#29), support MUA setups such as with mutt (#31) which may or may not relate to future Autocrypt specifications.  I am therefore considering to re-brand the effort to a new name to avoid confusion with users and developers.  The new name should not be tied much to autocrypt.  The "autocrypt" page on PyPI would then become a placeholder package that links to the new project and also https://github.com/juga0/pyac 

I'd appreciate hearing opinions from @azul, @fschulze, @juga0, @dkg and others before heading forward as each of you has been involved a bit in one way or another.

**Comment by juga0** [comment]
1. what would the new name?
2. how will you do to make https://pypi.python.org/pypi/autocrypt to point to 2 different tools?
3. from these 3 topics, which ones then you consider autocrypt related (maybe in future levels) and which not?
3.1. mailman integration
3.2. out of band verification
3.3. integration with mutt

From #19 it seemed to be all those autocrypt goals, or goals that pyac would not be able to achive because of pgpy.

**Comment by hpk42** [comment]
- pypi/autocrypt would contain a README which https-links to the other projects. 

- new name: not sure yet but this issue is not primarily about finding a name 

- mailman/oob/mutt issues are all autocrypt related but not about just a spec implementation -- i expect some of these efforts result in experiences which flow into possible future autocrypt specs  (which is true for any MUA or MUA-support impl)

**Comment by dkg** [comment]
Sounds like you're aiming to repurpose this repository more broadly than it had been traditionally targeted.  That's fine with me, and i have no objections to any of my past contributions being used in such a retargeting.

that said, if the focus is super broad it makes it rather difficult to tell when anyone would want to install it.  (i.e. if i'm a mutt user, do i care about a ton of utilities designed for bots?)  I tend to like software that is aimed at a specific use case, or framed around a particularl toolset.  vague and expansive mandates leave me a little lost.

So I don't know how to give advice on how you want to re-focus your python module here, but if you do want to refocus it, i'd start with rewriting the README to explain the intended scope of the project.  then the "rebranding" will probably follow more clearly from that.

You say "this issue is not primarily about finding a name", but that's what "rebranding" means to me, so perhaps the title of this ticket could be clearer.

as far as actually choosing a new name: if the module aims specifically at enhancing mutt, you could call it `muttenhancer` or `mutthelper`.  if it's generic MUA utilities, you could call it `mua-utils`.  If you rewrite the readme to clearly describe your intended scope, i'm happy to brainstorm new names with you :)

**Comment by hpk42** [comment]
thanks for the feedback. I agree scope is not quite clear yet and it might turn out that splitting functionality into multiple packages makes sense.  I'd like to to that only after there is a need, not a-priori.  maintaining and testing several packages is more effort than just one, especially if things are fast moving. 

#33 deals with splitting into a pure python core and the command line utility on top.  Internally there is a split already and also the bot could be factored out but for now, and while i intend to hack quite a bit on https://github.com/hpk42/py-autocrypt/milestone/1 and other issues i do not want to think a-priori think too much about proper splits.   I just want to avoid confusion for folks who expect a "pure" python example autocrypt implementation, focused on the spec and nothing else.

**Comment by dkg** [comment]
i agree with your concerns, fwiw.  i think autocrypt is a *feature* and not an implementation.  as such, it would be a feature of any set of MUA tools, and it doesn't make sense to name the set of MUA tools after only one of its features.

**Comment by hpk42** [comment]
#36 now contains a tentative rework of the READMEs and the home page.

**Comment by hpk42** [comment]
#36 has been merged, the new name is ``muacrypt``.
